server.port=${SERVER_PORT:5000}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost/evernet}
spring.data.mongodb.auto-index-creation=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION:true}
evernet.node.endpoint=${EVERNET_NODE_ENDPOINT:localhost:5000}
