server.port=${SERVER_PORT:8000}
server.address=${SERVER_ADDRESS:0.0.0.0}
spring.datasource.url=jdbc:sqlite:evernet.db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
evernet.jwt.secret.key=${EVERNET_JWT_SECRET_KEY:jwt.secret.jwt.secret.jwt.secret.jwt.secret.jwt.secret}
evernet.vertex=${EVERNET_VERTEX:localhost:8000}