server.address=${SERVER_ADDRESS:0.0.0.0}
server.port=${SERVER_PORT:5000}
spring.datasource.url=jdbc:sqlite:${DATABASE_FILE:evernet.sqlite}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.task.scheduling.pool.size=10
